version: '3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
  app:
    image: lukehaas/paper-pi
    ports:
      - "8001:8001"
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - ./.env
    tty: true
volumes:
  mongo-data:
